{% set name = "phonopy" %}
{% set version = "2.40.0" %}
{% set sha256 = "65e8cb40b8feecba070142264ff495fd72b9f7f8bfd0b064a1c88ce4efb2eee6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:  # Tentavive to fix the entry points
    - phonopy = phonopy.scripts.phonopy:run
    - phonopy-load = phonopy.scripts.phonopy_load:run
    - phonopy-bandplot = phonopy.scripts.phonopy_bandplot:run
    - phonopy-calc-convert = phonopy.scripts.phonopy_calc_convert:run
    - phonopy-crystal-born = phonopy.scripts.phonopy_crystal_born:run
    - phonopy-gruneisen = phonopy.scripts.phonopy_gruneisen:run
    - phonopy-gruneisenplot = phonopy.scripts.phonopy_gruneisenplot:run
    - phonopy-pdosplot = phonopy.scripts.phonopy_pdosplot:run
    - phonopy-propplot = phonopy.scripts.phonopy_propplot:run
    - phonopy-qha = phonopy.scripts.phonopy_qha:run
    - phonopy-tdplot = phonopy.scripts.phonopy_tdplot:run
    - phonopy-vasp-born = phonopy.scripts.phonopy_vasp_born:run
    - phonopy-vasp-efe = phonopy.scripts.phonopy_vasp_efe:run
    - phonopy-qe-born = phonopy.scripts.phonopy_qe_born:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pip
    - scikit-build-core
    - nanobind
    - cmake
    - make  # [not win]
    - ninja  # [win]    
    - setuptools_scm
    - llvm-openmp  # [osx or arm64]
    - libgomp      # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - spglib
    - pip
    - scikit-build-core
    - nanobind
    - cmake
    - make  # [not win]
    - ninja  # [win]    
    - setuptools_scm
  run:
    - python
    - spglib
    - matplotlib-base
    - h5py
    - scipy
    - pyyaml
    - symfc >=1.3.0

test:
  requires:
    - pytest
    - pip
  imports:
    - phonopy
  source_files:
    - test
  commands:
    - pip check
    - pytest -sv test/harmonic/test_dynamical_matrix.py::test_dynmat
    - pytest -sv test/phonon/test_tetrahedron_mesh.py::test_Amm2
    - pytest -sv test/phonon/test_mesh.py
    - pytest -v

about:
  home: https://phonopy.github.io/phonopy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Phonopy is an open source package for phonon calculations at harmonic and quasi-harmonic levels.

  description: |
    Phonopy is an open source package for phonon calculations at harmonic and quasi-harmonic levels.
    It works with multiple DFT programs (VASP, VASP DFPT, Abinit, Pwscf, Siesta, Elk, FHI-aims, Wien2k)
    as sources of inter-atomic forces and uses finite displacement method and symmetry relations
    for calculating elements of dynamical matrix. It works for all crystal symmetries and provides
    (among others)  phonon band structure, phonon DOS and partial-DOS, phonon thermal properties
    (free energy, heat capacity, and entropy), phonon group velocity, mean square displacements,
    irreducible representations of normal modes, quasi-harmonic approximation (thermal expansion,
    heat capacity at constant pressure), mode Grüneisen parameters, non-analytical-term correction
    (LO-TO splitting). It also provides Python API for use as a library.

  doc_url: https://phonopy.github.io/phonopy/
  dev_url: https://github.com/atztogo/phonopy/

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
    - bocklund
